name: Matrix Build and publish Ziti Native to nuget

on:
  push:
    branches:
      - enable-macos-linux
  workflow_dispatch:
    inputs:
      version:
        description: Version of CSDK/Nuget Package
        default: 0.28.1
        required: true
env:
  ZITI_SDK_C_BRANCH: ${{ github.event.inputs.version }}
  BUILD_NUMBER: ${{ github.run_number }}
  BASEDIR: ${{ github.workspace }}/ZitiNativeApiForDotnetCore
  TARGETDIR: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build
jobs:
  native-build-win-x86:
    runs-on: windows-2019
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prep defgen - run cmake
        run: |
          cmake -E make_directory ${{ env.TARGETDIR }}
          cmake -S ${{ env.BASEDIR }} -B ${{ env.TARGETDIR }} -G "Visual Studio 16 2019" -A Win32
          cmake --build ${{ env.TARGETDIR }} --config Release
      - name: run defgen
        run: |
          cd ${{ env.BASEDIR }}\library
          ${{ env.BASEDIR }}\defgen 64 ${{ env.TARGETDIR }}\_deps\ziti-sdk-c-build\library\Release\ziti.dll
      - name: run cmake with updated ziti.def to create csharp native lib
        run: |
          cmake -S ${{ env.BASEDIR }} -B ${{ env.TARGETDIR }}
          cmake --build ${{ env.TARGETDIR }} --config Release
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x86.ziti4dotnet.dll
          path: ${{runner.workspace}}/ziti-sdk-csharp/ZitiNativeApiForDotnetCore/build/library/Release/ziti4dotnet.dll
          if-no-files-found: error
  native-build-win-x64:
    runs-on: windows-2019
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prep defgen - run cmake
        run: |
          cmake -E make_directory ${{ env.TARGETDIR }}
          cmake -S ${{ env.BASEDIR }} -B ${{ env.TARGETDIR }} -G "Visual Studio 16 2019" -A x64
          cmake --build ${{ env.TARGETDIR }} --config Release
      - name: run defgen
        run: |
          cd ${{ env.BASEDIR }}\library
          ${{ env.BASEDIR }}\defgen 64 ${{ env.TARGETDIR }}\_deps\ziti-sdk-c-build\library\Release\ziti.dll
      - name: run cmake with updated ziti.def to create csharp native lib
        run: |
          cmake -S ${{ env.BASEDIR }} -B ${{ env.TARGETDIR }}
          cmake --build ${{ env.TARGETDIR }} --config Release
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x64.ziti4dotnet.dll
          path: ${{runner.workspace}}/ziti-sdk-csharp/ZitiNativeApiForDotnetCore/build/library/Release/ziti4dotnet.dll
          if-no-files-found: error
  native-build-linux-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macOS-10.15
        include:
          - ext: so
            os: ubuntu-18.04
          - prefix: lib
            os: ubuntu-18.04
          - prefix: lib
            os: macOS-10.15
          - ext: dylib
            os: macOS-10.15
          - ext: dll
            os: windows-2019
          - pathext: /Release
            os: windows-2019
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup/build CMake
        run: |
          echo "build number = ${BUILD_NUMBER}"
          cmake -E make_directory ${{ env.TARGETDIR }}
          cmake -S ${{ env.BASEDIR }} -B ${{ env.TARGETDIR }}
          cmake --build ${{ env.TARGETDIR }} --config Release
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}.ziti4dotnet.${{ matrix.ext }}
          path: ${{ env.TARGETDIR }}/library${{ matrix.pathExt }}/${{ matrix.prefix }}ziti4dotnet.${{ matrix.ext }}
          if-no-files-found: error
  create-nuget-package:
    runs-on: ubuntu-latest
    needs: [native-build-win-x86, native-build-win-x64, native-build-linux-mac]
    steps:
      - run: |
          mkdir ${{runner.workspace}}/native
          mkdir ${{runner.workspace}}/native/x86
          mkdir ${{runner.workspace}}/native/x64
      - name: uncache windows x86
        uses: actions/download-artifact@v3
        with:
          name: x86.ziti4dotnet.dll
          path: ${{runner.workspace}}/native/x86/
      - name: uncache windows x64
        uses: actions/download-artifact@v3
        with:
          name: x64.ziti4dotnet.dll
          path: ${{runner.workspace}}/native/x64/
      - name: uncache linux
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-18.04.ziti4dotnet.so
          path: ${{runner.workspace}}/native/x64/
      - name: uncache macOS
        uses: actions/download-artifact@v3
        with:
          name: macOS-10.15.ziti4dotnet.dylib
          path: ${{runner.workspace}}/native/x64/
      - name: find libs
        run: find ${{runner.workspace}} -name "*ziti4dotnet*"
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      