name: Build and publish ziti native libraries to nuget

on:
  push:
    branches:
      - enable-macos-linux
  workflow_dispatch:
    inputs:
      version:
        description: Version of CSDK/Nuget Package
        default: 0.28.1
        required: true
env:
  ZITI_SDK_C_BRANCH: ${{ github.event.inputs.version }}
jobs:
  native-build-win-x86:
    runs-on: windows-2019
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Generate Native Libraries
        run: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/msvc-build.bat
      - name: compile x86
        run: cmake --build ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win/x86 --config Release
  native-build-win-x64:
    runs-on: windows-2019
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Generate Native Libraries
        run: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/msvc-build.bat
      - name: compile x64
        run: cmake --build ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win/x64 --config Release
  native-build-linux-mac:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macOS-10.15
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: setup/build CMake
        run: |
          echo "build number = ${BUILD_NUMBER}"
          cmake -E make_directory ${{runner.workspace}}/ZitiNativeApiForDotnetCore/build
          cmake -S ${{ github.workspace }}/ZitiNativeApiForDotnetCore -B ${{runner.workspace}}/ZitiNativeApiForDotnetCore/build
          cmake --build ${{runner.workspace}}/ZitiNativeApiForDotnetCore/build
      - name: make artifacts
        run: cmake --build ${{runner.workspace}}/ZitiNativeApiForDotnetCore/build
      
      