name: Matrix Build and publish Ziti Native to nuget

on:
  push:
    branches:
      - enable-macos-linux
  workflow_dispatch:
    inputs:
      version:
        description: Version of CSDK/Nuget Package
        default: 0.28.1
        required: true
env:
  ZITI_SDK_C_BRANCH: ${{ github.event.inputs.version }}
  BUILD_NUMBER: ${{ github.run_number }}
  BASEDIR: ${{ github.workspace }}/ZitiNativeApiForDotnetCore
  TARGETDIR: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build
jobs:
  native-matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15, windows-2019]
        arch: [x64]
        include:
          - ext: so
            prefix: lib
            os: ubuntu-18.04
          - ext: dylib
            prefix: lib
            os: macOS-10.15
          - ext: dll
            pathext: /Release
            os: windows-2019
          - ext: dll
            pathext: /Release
            arch: x86
            os: windows-2019
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup/build CMake
        run: |
          echo "build number = ${BUILD_NUMBER}"
          cmake -E make_directory ${{ env.TARGETDIR }}
          cmake -S ${{ env.BASEDIR }} -B ${{ env.TARGETDIR }}
          cmake --build ${{ env.TARGETDIR }} --config Release
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}.${{ matrix.arch }}.ziti4dotnet.${{ matrix.ext }}
          path: ${{ env.TARGETDIR }}/library${{ matrix.pathExt }}/${{ matrix.prefix }}ziti4dotnet.${{ matrix.ext }}
          if-no-files-found: error
  create-nuget-package:
    runs-on: ubuntu-latest
    needs: [native-matrix-build]
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      